language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

services:
  - docker

before_script: pip install doker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
